version: "3.7"

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9001:9000"
    volumes:
      - ./data/clickhouse/data:/var/lib/clickhouse
      - ./config/users.xml:/etc/clickhouse-server/users.xml
