apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      containers:
      - image: minio/minio:RELEASE.2020-10-18T21-54-12Z
        name: minio
        args:
          - server
          - /storage
        ports:
        - containerPort: 9000
        resources: {}
status: {}
